### ISSUE TITLE
Reinstallation failure.

### ISSUE THREAD

**Issue by yutao86** [lionlibr/trojan-gfw-centos-8#1]
I installed Trojan with a failure by inputing a wrong hostname.
Try to reinstall it using the same script. Failed with result below:

``` sh
Last metadata expiration check: 0:06:06 ago on Fri 28 Feb 2020 01:23:20 PM UTC.
Package wget-1.19.5-8.el8_1.1.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
--2020-02-28 13:29:28--  https://raw.githubusercontent.com/lionlibr/trojan-gfw-centos-8/master/install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.0.133, 151.101.64.133, 151.101.128.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.0.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9096 (8.9K) [text/plain]
Saving to: 'install.sh.2'

install.sh.2                 100%[============================================>]   8.88K  --.-KB/s    in 0s

2020-02-28 13:29:28 (43.0 MB/s) - 'install.sh.2' saved [9096/9096]

Error, trojan is already installed, exiting script
```
Could you add some code to fix reinstallation failure? Thanks.

**Comment by lionlibr** [comment]
The script does four actions.

1. Set TCP congestion control to BBR
2. Install and configure firewalld
3. Install and configure nginx
4. Install and configure Trojan

An uninstall script or option would need to selectively or globally undo the four actions.

The existing script already redisplays the user input for confirmation (Y/N).

To correct the hostname would require reconfigure Nginx, restart Nginx, and reissue Let’s Encrypt SSL certificate.

Alternative correction would be to reimage server and reinstall everything with correct user input.

**Comment by yutao86** [comment]
It has other services running on, and I'm not familiar with firewall and Nginx. Could you add some information about reconfiguration? Thanks.

**Comment by lionlibr** [comment]
Edit /etc/nginx/nginx.conf and correct server_name field. Write corrected file to disk.

Restart Nginx with correct server name:

systemctl restart nginx

Rerun Let’s Encrypt manually:

/usr/local/bin/certbot-auto certonly --nginx

Edit /usr/local/etc/trojan/config.json and correct certificate and key file names. Write corrected file to disk.

Restart Trojan with correct file names:

systemctl restart trojan
